# Generated by Django 5.2.6 on 2025-10-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
            ],
            options={
                'permissions': [('can_create', 'Can create book'), ('can_delete', 'Can delete book'), ('can_edit', 'Can edit book'), ('can_view', 'Can view book')],
            },
        ),
    ]
