# Generated by Django 5.2.6 on 2025-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
